Added config and analysis files for Run 3 analysis.
uhh-cms/mttbar pull request #8
Opened 2024-10-22 11:46 UTC by jomatthi

This PR adds directories storing the Run 2 and Run 3 config and analysis files in separate places. It also adds a first version for a Run 3 config built from the ```config_2017``` and the [Run 3 config](https://github.com/uhh-cms/topsf/blob/master/topsf/config/run3/config_sf.py) used in the topsf analysis. This config needs to be tested.

2024-11-07 15:26 UTC, jomatthi commented
This pull request includes updates and improvements to the configuration and selection scripts for the `mtt` analysis, specifically for Run 2 and Run 3 datasets. The changes include renaming and restructuring files, adding new configuration parameters, and moving the selection criteria to the specific run configs.

### Configuration Updates:
* Updated the `default_analysis` path in `law.cfg` to use the new Run2 directory structure.
* Renamed `mtt/config/analysis_mtt.py` to `mtt/config/Run2/analysis_mtt.py` and updated import paths accordingly.
* Added new configuration parameters for b-tagging, top tagging, lepton selection, jet selection, and MET selection in `mtt/config/Run2/config_2017.py`. 

### New Run 3 Configuration:
* Added new configuration files `mtt/config/Run3/*` for Run 3 `mtt` analysis.
* Used Run 2 configuration parameters where possible. Changes needed:
   * highpt muon triggers: `TkMu100` -> `HighPtTkMu100`, remove `OldMu100`
   * electron isolation req.
   * top tagging algorithm: `DeepAK8` -> `ParticleNet` 

### Selection and Weighting Updates:
* Updated the `weights` function in `mtt/production/weights.py` to conditionally apply weights based on the run period as some weights are not available for Run 3 yet.
* Updated the `data_trigger_veto` function in `mtt/selection/data_trigger_veto.py` to handle `egamma` datasets used in Run 3.

2024-11-15 14:11 UTC, dsavoiu requested changes
Thanks a lot for the PR @jomatthi! This looks overall very good to me, I only have a few suggestions inline below and a few general points about the naming/structure of files:

- [ ] I would stick to the convention of using lowercase names for directory names that are part of Python modules, so let's go with `run2` or `run3` for the subdirectories of the `config` folder.
- [ ] For the config files I would suggest to also replace the convention `config_<year>.py` by just `config_mtt.py`, since the year-dependent stuff is ideally handled as part of the `add_config` function inside.
- [ ] On a related note, it would be good to have the `add_config` function in the `run2` config as well rather than the config being at the module level, so that the structure is completely analogous between run2 and run3.

Could you go through the points above and below and implement the changes?

2024-11-15 14:11 UTC, dsavoiu commented on law.cfg
> +default_analysis: mtt.config.Run2.analysis_mtt.analysis_mtt
I would use lowercase `run2` here for consistency with the other analyses and also since the config is technically a Python module which are typically named using all-lowercase by convention.
```suggestion
default_analysis: mtt.config.run2.analysis_mtt.analysis_mtt
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run2/config_2017.py
> +    },
I just checked the TWiki and it seems that the regular and mass-decorrelated tagger values are switched around. So the correct config should probably read:
```suggestion
        # regular tagger
        "top": 0.725,
        "w": 0.925,
        # mass-decorrelated tagger
        "top_md": 0.344,
        "w_md": 0.739,
    },
```

@jomatthi Could you double-check and adapt this if needed?

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run2/config_2017.py
> +            "value": 4,
Since the `pfIsoId` only contains a single value per muon, corresponding to the tightest working point passed, one should adapt the selection code to also select muons that have `pfIsoId` value greater than or equal to the one on the config (i.e. pass a tighter selection than the value given here). For clarity, it would be good to reflect this in the config key name, so I would suggest to change this from `value` to `min_value`:
```suggestion
            "min_value": 4,
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run2/config_2017.py
> +        "msd": [105, 210],
Suggest to use `msoftdrop` here for consistency with NanoAOD column names.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run2/config_2017.py
> -    "dy": ["dy_*"],
Why is `dy` dropped from the dataset groups?

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/analysis_mtt.py
> +# campaign_run3_2023_postBPix_nano_v12.x.BPix = "post"
Suggest to use the `import as` syntax to set the aliases directly on import:
```suggestion
import cmsdb.campaigns.run3_2022_preEE_nano_v12 as campaign_run3_2022_preEE_nano_v12
import cmsdb.campaigns.run3_2022_postEE_nano_v12 as campaign_run3_2022_postEE_nano_v12
# import cmsdb.campaigns.run3_2023_preBPix_nano_v12 as campaign_run3_2023_preBPix_nano_v12
# import cmsdb.campaigns.run3_2023_postBPix_nano_v12 as campaign_run3_2023_postBPix_nano_v12

campaign_run3_2022_preEE_nano_v12.x.EE = "pre"
campaign_run3_2022_postEE_nano_v12.x.EE = "post"
# campaign_run3_2023_preBPix_nano_v12.x.BPix = "pre"
# campaign_run3_2023_postBPix_nano_v12.x.BPix = "post"
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +            "w_md": 0.925,
Here the MD/non-MD appear switched as well.
```suggestion
            # regular tagger
            "top": 0.725,
            "w": 0.925,
            # mass-decorrelated tagger
            "top_md": 0.344,
            "w_md": 0.739,
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +                "value": 4,
Would go for `min_value` here (see comment for Run2 config).
Also, it would be good to add a comment here explaining what the value `4` means.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +    if cfg.x.run == 3:
No need to check for this explicitly since this is a Run 3 config by construction.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +    if cfg.x.run == 3:
Can drop the `if` statement here (see above).

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +    if cfg.x.run == 3:
Can drop the `if` statement here (see above).

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +                "value": 3,
Probably should also be `min_value`? (see above)
Should also explain the value `3` in a comment

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +                        # "OldMu100",
There doesn't seem to be an `OldMu100` trigger in Run3 anymore, so this comment can be safely removed.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +    # FIXME not needed any more? Update to 2022 if needed
This correction deals with the ECAL L1 prefiring, which was fixed in 2018 and is no longer an issue in Run3. There are, however, other prefiring effects in Run 3 which are due to muons. These are currently under investigation and there is no recipe on how to treat them. So I think can probably remove or at least comment out this part of the config.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/production/weights.py
> +            }
This could be moved to after the default `self.produces` is filled to avoid an additional `if` statement.

2024-11-15 14:11 UTC, dsavoiu commented on mtt/selection/jets.py
> +            pt_rel > sel_params.pt_rel,
Should add `min_` to the config param name to make the cut more explicit.
```suggestion
            pt_rel > sel_params.min_pt_rel,
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/selection/jets.py
> +        sel = ak.all(lepton_jet_deltar > sel_params.delta_r, axis=-1)
Should add `min_` to the config param name to make the cut more explicit.
```suggestion
        sel = ak.all(lepton_jet_deltar > sel_params.min_delta_r, axis=-1)
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +        "pt_rel": 25,
Suggest to add `min_` to param names to make the cuts more explicit.
```suggestion
        "min_delta_r": 0.4,
        "min_pt_rel": 25,
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +            "msd": [105, 210],
Suggest to change to `msoftdrop` for consistency with the NanoAOD column.
```suggestion
            "msoftdrop": [105, 210],
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/selection/lepton.py
> +        (lepton[sel_params.iso.column] == sel_params.iso.value) &
```suggestion
        (lepton[sel_params.iso.column] >= sel_params.iso.min_value) &
```

2024-11-15 14:11 UTC, dsavoiu commented on mtt/config/Run3/config_2022.py
> +                    "value": 2,
Suggest to add a comment here explaining the value `2`.

2024-11-15 15:02 UTC, jomatthi commented on mtt/config/Run2/config_2017.py
> +    },
Good catch, thank you!

2024-11-15 15:08 UTC, jomatthi commented on mtt/config/Run2/config_2017.py
> -    "dy": ["dy_*"],
It is a duplicate from the definition in a few lines earlier.

2024-11-15 15:29 UTC, jomatthi commented on mtt/config/Run3/config_2022.py
> +    # FIXME not needed any more? Update to 2022 if needed
I removed the ECAL L1 prefixing correction files from the 2022 config. As soon as the muon preferring corrections are there, they can be added into the config.

2025-01-13 12:30 UTC, jomatthi commented
Hi @dsavoiu,
Thank you for the review and the comments. They have been implemented in the last commits.
Before merging this PR into the master branch I want to update columnflow to the latest master which will require some adapting of the config files.

2025-01-14 17:31 UTC, jomatthi commented
The latest commits include the update of columnflow and fixes some broken calculations due to the updated software. The testing workflow in ```workflow_scripts/test_workflow.sh``` _should_ now work, both locally and via htcondor.

While fixing the issues with the crossproduct and delta_r calculations (due to some coffea/vector software update), I realised that the relative pt between the lepton and the jet closest to the lepton is calculated differently in the ```lepton_jet_2d_selection``` [selector](https://github.com/uhh-cms/mttbar/blob/master/mtt/selection/jets.py#L298) and in the ```jet_lepton_features``` [producer](https://github.com/uhh-cms/mttbar/blob/master/mtt/production/features.py#L104). The selector uses ```p```, while the producer uses ```pt```. In [this](https://github.com/uhh-cms/mttbar/pull/8/commits/94bb2d56d6c8f948808b4399fdcc8407e6c4d949) commit I changed the later to also use ```p``` as this should also be the correct way to calculate the relative pt in this context.

Let me know if you see anything still needing to be changed before merging this PR.

2025-01-31 14:05 UTC, dsavoiu approved these changes
Hi @jomatthi, this looks good, thanks a lot for the updates! I think these changes address the most important outstanding issues, so I would go ahead and merge them :tada:

2025-01-31 14:06 UTC, merged